#!/usr/bin/env bash
# Preflight check: verify podman, systemd, Quadlet, images, and env are ready.
# Usage: ./check.sh          (run standalone)
#        source check.sh     (sourced by other scripts; exits on failure)
set -euo pipefail
export XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}"
export DBUS_SESSION_BUS_ADDRESS="${DBUS_SESSION_BUS_ADDRESS:-unix:path=$XDG_RUNTIME_DIR/bus}"

PASS=0
FAIL=0
WARN=0

ok()   { PASS=$((PASS+1)); printf '  \033[32m✓\033[0m %s\n' "$1"; }
fail() { FAIL=$((FAIL+1)); printf '  \033[31m✗\033[0m %s\n' "$1"; }
warn() { WARN=$((WARN+1)); printf '  \033[33m!\033[0m %s\n' "$1"; }

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
QUADLET_DIR="$HOME/.config/containers/systemd"

echo "=== NetFlower preflight check ==="
echo ""

# --- Podman ---
echo "Podman:"
if command -v podman &>/dev/null; then
  ok "podman found ($(podman --version 2>/dev/null | head -1))"
else
  fail "podman not found in PATH"
fi

# --- systemd user session ---
echo "Systemd user session:"
if [[ -d "$XDG_RUNTIME_DIR" ]]; then
  ok "XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR"
else
  fail "XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR does not exist (is the user session active?)"
fi

if systemctl --user list-units --type=service &>/dev/null; then
  ok "systemctl --user is reachable"
else
  fail "systemctl --user is not reachable (check XDG_RUNTIME_DIR or user session)"
fi

# --- Lingering ---
echo "Lingering:"
LINGER=$(loginctl show-user "$(whoami)" --property=Linger 2>/dev/null | cut -d= -f2)
if [[ "$LINGER" == "yes" ]]; then
  ok "Linger=yes (services survive logout and start at boot)"
else
  fail "Linger is not enabled. Run: sudo loginctl enable-linger $(whoami)"
fi

# --- Quadlet container files ---
echo "Quadlet files ($QUADLET_DIR):"
for name in netflower-api netflower-frontend; do
  if [[ -f "$QUADLET_DIR/$name.container" ]]; then
    ok "$name.container exists"
  else
    fail "$name.container missing — copy it to $QUADLET_DIR/"
  fi
done

# --- Generated services ---
echo "Generated services:"
systemctl --user daemon-reload 2>/dev/null
for name in netflower-api netflower-frontend; do
  if systemctl --user list-unit-files "$name.service" 2>/dev/null | grep generated &>/dev/null; then
    ok "$name.service generated by Quadlet"
  else
    fail "$name.service not found (run: systemctl --user daemon-reload)"
  fi
done

# --- Container images ---
echo "Container images:"
for tag in localhost/netflower-server:latest localhost/netflower-frontend:latest; do
  if podman image exists "$tag" 2>/dev/null; then
    ok "$tag exists"
  else
    fail "$tag not built — run: ./build.sh"
  fi
done

# --- Service runtime status ---
echo "Service status:"
for name in netflower-api netflower-frontend; do
  state=$(systemctl --user is-active "$name.service" 2>/dev/null || true)
  case "$state" in
    active)   ok "$name.service is running" ;;
    inactive) warn "$name.service is stopped (start with: systemctl --user start $name)" ;;
    failed)   fail "$name.service is in failed state (check: systemctl --user status $name)" ;;
    *)        warn "$name.service state: $state" ;;
  esac
done

# Check for ghost units from the old podman-generate-systemd era
for old in container-netflower-api container-netflower-frontend; do
  state=$(systemctl --user is-active "$old.service" 2>/dev/null || true)
  if [[ "$state" == "failed" ]]; then
    warn "Stale unit $old.service is in failed state (run: systemctl --user reset-failed $old.service)"
  fi
done

# --- .env file ---
echo "Environment:"
ENV_FILE="$ROOT/.env"
if [[ -f "$ENV_FILE" ]]; then
  ok ".env file found at $ENV_FILE"
  for var in DB_HOST DB_USER DB_PASSWORD DB_NAME JWT_SECRET; do
    if grep -q "^${var}=" "$ENV_FILE" 2>/dev/null; then
      if [[ "$var" == "JWT_SECRET" ]] && grep -q "^JWT_SECRET=change_this_secret_key" "$ENV_FILE"; then
        warn "$var is still the default placeholder — change it before production"
      else
        ok "$var is set"
      fi
    else
      fail "$var missing from .env"
    fi
  done
else
  fail ".env file not found at $ENV_FILE"
fi

# --- Summary ---
echo ""
echo "=== Results: $PASS passed, $FAIL failed, $WARN warnings ==="
if [[ $FAIL -gt 0 ]]; then
  echo "Fix the failures above before running other scripts."
  exit 1
fi
if [[ $WARN -gt 0 ]]; then
  echo "Warnings are non-blocking but should be addressed."
fi
exit 0
